name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Install theme-check
        run: gem install theme-check
      - name: Run theme-check
        run: theme-check
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install npm deps
        run: npm ci
      - name: Run ESLint
        run: npm run lint:js
